---

- name: update package cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: update system
  ansible.builtin.apt:
    name: "*"
    state: latest
  become: true

- name: apply network changes
  ansible.builtin.command: "ifreload -a"
  become: true
